app = "yt-dlp-mp3"  # שנה לשם האפליקציה שלך
primary_region = "iad"

[env]
FLY_APP_NAME = "yt-dlp-mp3"

[build]
  image = "python:3.12-slim"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "pip install --upgrade yt-dlp && uvicorn main:app --host 0.0.0.0 --port 8080"
